SELECT * FROM EMP02;



CREATE VIEW V_EMP02
AS
SELECT ENAME,JOB,DNO
FROM EMP02;


CREATE TABLE EMP02 AS

SELECT * FROM EMPLOYEE;

SELECT * FROM DEPARTMENT;

SELECT 'John' AS NAME, 'Engineer' AS JOB
FROM dual;

CREATE VIEW V_DEPT02 AS
WITH temp_data AS (
    SELECT 'John' AS NAME, 'Engineer' AS JOB
    FROM DUAL)
SELECT * FROM DEPARTMENT;


CREATE VIEW V_JOIN AS
WITH temp_data AS (
    SELECT 'John' AS NAME, 'Engineer' AS JOB
    FROM DUAL
)
SELECT * FROM EMPLOYEE;

SELECT 컬러명 FROM 테이블명 

CREATE VIEW MY_EMP_VIEW AS
SELECT EMPNO, ENAME, JOB
FROM EMP;

SELECT *FROM V_EMP02;



SELECT * FROM USER_VIEWS;



CREATE VIEW V_JOIN
AS
SELECT ENAME,JOB,SALARY,ENAME FROM V_JOIN;
FROM EMP02 E
JOIN DEPT02 D
ON E.DNO = D.DNO
WHERE SALARY >= 2500;

CREATE TABLE EMP02
AS
SELECT *FROM ENO,ENAME,SALARY,COMMISSION,JOB,HIREDATE;

CREATE TABLE EMP02 AS
SELECT ENO, ENAME, SALARY, COMMISSION, JOB, HIREDATE
FROM YOUR_EXISTING_TABLE; -- 여기에 원본 테이블 이름을 지정해야 합니다.


SELECT ENAME,JOB,SALARY,DNAME,LOC
FROM EMP02 E
JOIN DEPT02 D
ON E.DNO = D.DNO
WHERE SALARY >=2500;


FROM EMPLOYEE
WHERE SALARY > 1500 ;

CRETE TABLE EMP02
AS
SELECT * FROM EMPLOYEE;


CREATE TABLE DEPT02
AS
SELECT *FROM DEPARTMENT;

SELECT *FROM V_JOIN ;

-- EMPLOYEE ,DEPARTMENT 테이블의 부서별로 최소월급을 받는 사원의직책,부서명,부서위치를 출력하되  최소 월급이 1500 이상인경우
-- 사원 정보를 출력 , 부서번호 20번은 제외하고 
-- 뷰안에 쿼리를 저장하고 ,뷰를 실행해서 출력한다 .

-- 부서별로 최소월급을 받는사원 정보를 출력하는 VIEW ,20Q부서는제오 ;

CREATE VIEW V_JOIN2
AS
SELECT ENAME 사원이름, JOB 직책, DNAME 부서명, LOC 부서위치
FROM EMPLOYEE E 
JOIN DEPARTMENT D
ON E.DNO = D.DNO
WHERE SALARY IN ( 
 -- 부서별로 최소월급
 SELECT MIN(SALARY)FROM EMPLOYEE 
 WHERE DNO <> 
 GROUP BY DNO
 HAVING MIN(SALARY)>1500 
);

CREATE VIEW V_JOIN2
AS
SELECT ENAME AS "사원이름", JOB AS "직책", DNAME AS "부서명", LOC AS "부서위치"
FROM EMPLOYEE E 
JOIN DEPARTMENT D ON E.DNO = D.DNO
WHERE SALARY IN (
    SELECT MIN(SALARY)
    FROM EMPLOYEE 
    WHERE DNO = E.DNO
    GROUP BY DNO
    HAVING MIN(SALARY) > 1500
);
--
SELECT *
FROM V_JOIN2;
--
CREATE VIEW V_JOIN3
AS
SELECT ENAME AS "사원이름", JOB AS "직책", DNAME AS "부서명", LOC AS "부서위치"
FROM EMPLOYEE E 
JOIN DEPARTMENT D ON E.DNO = D.DNO
WHERE SALARY IN (
    SELECT MIN(SALARY)
    FROM EMPLOYEE 
    WHERE DNO = E.DNO
    GROUP BY DNO
    HAVING MIN(SALARY) > 1500
);
--
SELECT * FROM V_JOIN3;
--

