
CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL,
    WINE_CODE VARCHAR2(6) NOT NULL,
    MEM_ID VARCHAR2(30) NOT NULL,
    SALE_AMOUNT VARCHAR2(5) NOT NULL,              
    SALE_PRICE VARCHAR2(6) NOT NULL, 
    SALE_TOT_PRICE VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_SALE_SALE_DATE PRIMARY KEY (SALE_DATE),
    CONSTRAINT FK_SALE_WINE_CODE 
 FOREIGN KEY (WINE_CODE) 
 REFERENCES SALE_WINE_TABLE(WINE_CODE), CONSTRAINT FK_SALE_MEM_ID FOREIGN KEY (MEM_ID) 
 REFERENCES SALE_MEMBER_TABLE(MEM_ID) 
);



   CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(6) NOT NULL,
    MEM_GRADE VARCHAR2(20) NOT NULL,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_BIRTH DATE DEFAULT SYSDATE NOT NULL,
    MEM_TEL VARCHAR2(20),
    MEM_PT VARCHAR2(10) NOT NULL,
    PRIMARY KEY (MEMBER_ID, MEM_GRADE)
);



CREATE TABLE GRADE_PT_RADE (
    MEM_GRADE VARCHAR2(20) NOT NULL PRIMARY KEY,
    GRADE_PT NUMBER(3,2)
);




CREATE TABLE TODAY (
    TODAY_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    TODAY_SENS_VALUE NUMBER(3),
    TODAY_INTELL_VALUE  NUMBER(3),
    TODAY_PHY_VALUE  NUMBER(3)
);



CREATE TABLE NATION (
    NATION_CODE VARCHAR2(26) NOT NULL PRIMARY KEY,
    NATION_NAME VARCHAR2(50)
);




CREATE TABLE WINE (
    WINE_CODE VARCHAR2(20) NOT NULL, 
    WINE_NAME VARCHAR2(100) NOT NULL,
    WINE_URL BLOB,
    NATION_CODE VARCHAR2(6),
    WINE_TYPE_CODE VARCHAR2(6),
    WINE_SUGAR_CODE NUMBER(2),
    WINE_PRICE NUMBER(15) NOT NULL,
    WINE_VINTAGE DATE DEFAULT SYSDATE,
    THEME_CODE VARCHAR2(6),
    TODAY_CODE VARCHAR2(6),
    CONSTRAINT PK_WINE PRIMARY KEY (WINE_CODE),
    CONSTRAINT FK_WINE 
        FOREIGN KEY (NATION_CODE, WINE_TYPE_CODE, THEME_CODE, TODAY_CODE)
        REFERENCES OTHER_TABLE(NATION_CODE, WINE_TYPE_CODE, THEME_CODE, TODAY_CODE)
    -- Add other columns as needed
);





CREATE TABLE THEME(
    THEME_COE VARCHAR2(6) NOT NULL PRIMARY KEY,
    THEME_NAME VARCHAR2(50) NOT NULL
);





CREATE TABLE STOCK_MANAGEMENT (
    STOCK_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    WINE_CODE VARCHAR2(6) NOT NULL,
    MANAGER_ID VARCHAR2(30) NOT NULL,
    WARE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STOCK_AMOUNT NUMBER(5) NOT NULL,
    CONSTRAINT FK_MANAGEMENT_WINECODE FOREIGN KEY (WINE_CODE) REFERENCES WINE(WINE_CODE),
    CONSTRAINT FK_MANAGEMENT_MANAGER_ID FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(MANAGER_ID)
);

    
    
    
CREATE TABLE MANAGER (
    MANAGER_ID VARCHAR2(30) NOT NULL PRIMARY KEY,
    MANAGER_PWD VARCHAR2(20) NOT NULL,
    MANAGER_FEL  VARCHAR2(20)
    );
    





CREATE TABLE WINE_TYPE (
    WINE_TYPE_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    WINE_TYPE_NAME  VARCHAR2(50) 
    );
    
    
    -----------------------------------------------------------------
    
    
    CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL,
    WINE_CODE VARCHAR2(6) NOT NULL,
    MEM_ID VARCHAR2(30) NOT NULL,
    SALE_AMOUNT NUMBER(10,2) NOT NULL,              
    SALE_PRICE NUMBER(10,2) NOT NULL, 
    SALE_TOT_PRICE NUMBER(15,2) NOT NULL,
    CONSTRAINT PK_SALE_SALE_DATE PRIMARY KEY (SALE_DATE),
    CONSTRAINT FK_SALE_WINE_CODE 
        FOREIGN KEY (WINE_CODE) 
        REFERENCES WINE(WINE_CODE),
    CONSTRAINT FK_SALE_MEM_ID 
        FOREIGN KEY (MEM_ID) 
        REFERENCES MEMBER(MEMBER_ID)
);

CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(6) NOT NULL,
    MEM_GRADE VARCHAR2(20) NOT NULL,
    MEM_PW VARCHAR2(20) NOT NULL,
    MEM_BIRTH DATE DEFAULT SYSDATE NOT NULL,
    MEM_TEL VARCHAR2(20),
    MEM_PT NUMBER(10,2) NOT NULL,
    PRIMARY KEY (MEMBER_ID, MEM_GRADE)
);

CREATE TABLE GRADE_PT_GRADE (
    MEM_GRADE VARCHAR2(20) NOT NULL PRIMARY KEY,
    GRADE_PT NUMBER(3,2)
);

CREATE TABLE TODAY (
    TODAY_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    TODAY_SENS_VALUE NUMBER(3),
    TODAY_INTELL_VALUE NUMBER(3),
    TODAY_PHY_VALUE NUMBER(3)
);

CREATE TABLE NATION (
    NATION_CODE VARCHAR2(26) NOT NULL PRIMARY KEY,
    NATION_NAME VARCHAR2(50)
);

CREATE TABLE WINE (
    WINE_CODE VARCHAR2(20) NOT NULL, 
    WINE_NAME VARCHAR2(100) NOT NULL,
    WINE_URL BLOB,
    NATION_CODE VARCHAR2(6),
    WINE_TYPE_CODE VARCHAR2(6),
    WINE_SUGAR_CODE NUMBER(2),
    WINE_PRICE NUMBER(15,2) NOT NULL,
    WINE_VINTAGE DATE DEFAULT SYSDATE,
    THEME_CODE VARCHAR2(6),
    TODAY_CODE VARCHAR2(6),
    CONSTRAINT PK_WINE PRIMARY KEY (WINE_CODE),
    CONSTRAINT FK_WINE 
        FOREIGN KEY (NATION_CODE, WINE_TYPE_CODE, THEME_CODE, TODAY_CODE)
        REFERENCES OTHER_TABLE(NATION_CODE, WINE_TYPE_CODE, THEME_CODE, TODAY_CODE) -- Replace with the correct table name
    -- Add other columns as needed
);

CREATE TABLE THEME (
    THEME_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    THEME_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE STOCK_MANAGEMENT (
    STOCK_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    WINE_CODE VARCHAR2(6) NOT NULL,
    MANAGER_ID VARCHAR2(30) NOT NULL,
    WARE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STOCK_AMOUNT NUMBER(5) NOT NULL,
    CONSTRAINT FK_MANAGEMENT_WINECODE 
        FOREIGN KEY (WINE_CODE) 
        REFERENCES WINE(WINE_CODE),
    CONSTRAINT FK_MANAGEMENT_MANAGER_ID 
        FOREIGN KEY (MANAGER_ID) 
        REFERENCES MANAGER(MANAGER_ID)
);

CREATE TABLE MANAGER (
    MANAGER_ID VARCHAR2(30) NOT NULL PRIMARY KEY,
    MANAGER_PWD VARCHAR2(20) NOT NULL,
    MANAGER_FEL  VARCHAR2(20) -- Complete the definition if needed
);

CREATE TABLE WINE_TYPE (
    WINE_TYPE_CODE VARCHAR2(6) NOT NULL PRIMARY KEY,
    WINE_TYPE_NAME VARCHAR2(50)
);
