

    CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL CONSTRAINT PK_SALE_SALE_DATE PRIMARY KEY, 
    WINE_CODE VARCHAR2(6)NOT NULL CONSTRAINT FK_SALE_WINE_CODE,
    MEM_ID VARCHAR2(30)NOT NULL CONSTRAINT FK_SALE_MEM_ID ,
    SALE_AMOUNT VCHAR2(5)NOT NULL,              
    SALE_PRICE VARCHAR2(6) NOT NULL, 
    SALE_TOT_PRICE VARCHAR2(15) NOT NULL
    );
    
    CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL CONSTRAINT PK_SALE_DATE PRIMARY KEY, 
    WINE_CODE VARCHAR2(6) NOT NULL CONSTRAINT FK_WINE_CODE REFERENCES SOME_TABLE(WINE_CODE),
    MEM_ID VARCHAR2(30) NOT NULL CONSTRAINT FK_MEM_ID REFERENCES ANOTHER_TABLE(MEM_ID),
    SALE_AMOUNT VARCHAR2(5) NOT NULL,              
    SALE_PRICE VARCHAR2(6) NOT NULL, 
    SALE_TOT_PRICE VARCHAR2(15) NOT NULL
);
    
    GENDER CHAR(1) CONSTRAINT CK_WINE_GENDER CHECK (GENDER IN ('W','IN')),
    WEIGHT NUMBER(5,2), -- 정수 전체4자리 ,소숫점 이하2자리 
    HIREDATE DATE DEFAULT SYSDATE,
    ADDR2 CHAR(10) DEFAULT '서울',
    AGE2 NUMBER DEFAULT 0
);

INSERT INTO MEMBER4(ID,PASS,ADDR,JUMIN,PHONE,AGE,WEIGHT,GENDER,HIREDATE,ADDR2,AGE2)
VALUES ('ABC','1234','서울','2225-4567','010-6546-7897',100,77.77,'W','22/11/11',30);




CREATE TABLE  ZIPCODE11 (
    ZIPCODE NUMBER(5) NOT NULL CONSTRAINT PK_ZIPCODE11_ZIPCODE PRIMARY KEY,
    SI_DO VARCHAR2(200) NOT NULL,
    GU_GUN VARCHAR2(200) NOT NULL,
    BUNGI VARCHAR2(200) NOT NULL 
    );
        
SELECT * FROM MEMBER4;

CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL CONSTRAINT PK_SALE_SALE_DATE PRIMARY KEY, 
    WINE_CODE VARCHAR2(6) NOT NULL CONSTRAINT FK_SALE_WINE_CODE,
    MEM_ID VARCHAR2(30) NOT NULL CONSTRAINT FK_SALE_MEM_ID,
    SALE_AMOUNT VARCHAR2(5) NOT NULL,              
    SALE_PRICE VARCHAR2(6) NOT NULL, 
    SALE_TOT_PRICE VARCHAR2(15) NOT NULL
);


CREATE TABLE SALE (
    SALE_DATE DATE NOT NULL,
    WINE_CODE VARCHAR2(6) NOT NULL,
    MEM_ID VARCHAR2(30) NOT NULL,
    SALE_AMOUNT VARCHAR2(5) NOT NULL,              
    SALE_PRICE VARCHAR2(6) NOT NULL, 
    SALE_TOT_PRICE VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_SALE_SALE_DATE PRIMARY KEY (SALE_DATE),
    CONSTRAINT FK_SALE_WINE_CODE FOREIGN KEY (WINE_CODE) REFERENCES OTHER_TABLE(WINE_CODE),
    CONSTRAINT FK_SALE_MEM_ID FOREIGN KEY (MEM_ID) REFERENCES ANOTHER_TABLE(MEM_ID)
);

 DROP TABLE MEMBER4;


COMMIT ;